'use strict';
const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const path=require('path');
const exporterPath=path.join(__dirname,'excel-export.js');
const source=fs.readFileSync(exporterPath,'utf8');
new vm.Script(source,{filename:'excel-export.js'});
const headers=['Item ID','Item No.','Section','Work Description','Unit','BOQ Quantity','Adopted Rate','BOQ Amount','Quantity Basis','Drawing / Reference','Change Classification','Approved Variation Quantity','Allowed Quantity','Change / Approval Reference','Remarks'];
assert.strictEqual(headers.length,15);
assert.deepStrictEqual(headers,['Item ID','Item No.','Section','Work Description','Unit','BOQ Quantity','Adopted Rate','BOQ Amount','Quantity Basis','Drawing / Reference','Change Classification','Approved Variation Quantity','Allowed Quantity','Change / Approval Reference','Remarks']);
const toNumber=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const variationAllowedQty=item=>{const c=item?.change;if(!c||c.classification==='Original BOQ Item')return Number(item.qty)||0;if(c.status!=='Approved')return 0;const q=Number(c.revisedQuantity);return Number.isFinite(q)&&q>=0?q:Number(item.qty)||0};
function mapBoq(item){const c=item.change||{},allowed=variationAllowedQty(item),qty=toNumber(item.qty),rate=toNumber(item.rate);const approvedVariation=allowed==null||qty==null?'':allowed-qty;const amount=rate==null||qty==null?null:qty*rate;return[item.id,item.no,item.section,item.desc,item.unit,qty,rate,amount,item.quantityBasis,item.drawingReference,c.classification||'',approvedVariation,allowed,c.status==='Approved'?(c.approvalReference||c.referenceNo||''):c.referenceNo||'',item.remarks]}
const a={id:'ITEM-a',no:'1',section:'Earthwork',desc:'Excavation',unit:'m3',qty:10,rate:125,quantityBasis:'Calculated',drawingReference:'D-01',remarks:'keep'};
assert.strictEqual(mapBoq(a)[0],'ITEM-a');
assert.strictEqual(mapBoq(a)[1],'1');
assert.strictEqual(mapBoq(a)[5],10);
assert.strictEqual(mapBoq(a)[6],125);
assert.strictEqual(mapBoq(a)[7],1250);
assert.strictEqual(mapBoq(a)[10],'');
const missingRate=mapBoq({...a,rate:''});
assert.strictEqual(missingRate[6],null);
assert.strictEqual(missingRate[7],null);
const approved=mapBoq({...a,change:{classification:'Variation',status:'Approved',revisedQuantity:14,approvalReference:'APR-1',referenceNo:'VAR-1'}});
assert.strictEqual(approved[10],'Variation');
assert.strictEqual(approved[11],4);
assert.strictEqual(approved[12],14);
assert.strictEqual(approved[13],'APR-1');
const proposed=mapBoq({...a,change:{classification:'Variation',status:'Proposed',revisedQuantity:14,approvalReference:'APR-2',referenceNo:'VAR-2'}});
assert.strictEqual(proposed[11],-10);
assert.strictEqual(proposed[12],0);
assert.strictEqual(proposed[13],'VAR-2');
const rejected=mapBoq({...a,change:{classification:'Variation',status:'Rejected',revisedQuantity:14,referenceNo:'VAR-3'}});
assert.strictEqual(rejected[11],-10);
assert.strictEqual(rejected[12],0);
const reordered=[{id:'ITEM-a',no:'1',qty:10},{id:'ITEM-b',no:'2',qty:20}];
const before=reordered.map(x=>x.id);reordered.reverse();assert.deepStrictEqual(reordered.map(x=>x.id).sort(),before.sort());
const sourceAssertions=[/s\(x\.id\)/,/s\(x\.no\)/,/n\(x\.qty\)/,/n\(x\.rate\)/,/variationAllowedQty\(x\)/,/\['Item ID','Item No\.','Section','Work Description','Unit','BOQ Quantity','Adopted Rate','BOQ Amount','Quantity Basis','Drawing \/ Reference','Change Classification','Approved Variation Quantity','Allowed Quantity','Change \/ Approval Reference','Remarks'\]/,/XLSX\.writeFile\(wb,/,/window\.downloadCivilKoshExcel=exportWorkbook/];
sourceAssertions.forEach(re=>assert.ok(re.test(source),`missing exporter contract: ${re}`));
['Measurement / MB','Quantity Abstract','Rate Analysis','IPC / Running Bill','Variation / Extra / Substituted','Evidence & Documents','Reports / Summary'].forEach(name=>assert.ok(source.includes(`makeSheet(wb,'${name}'`),`missing existing sheet: ${name}`));
console.log('BOQ Master mapping tests: PASS');