const sections=['Earthwork','Concrete','Reinforced Concrete','Masonry','Plaster & Finishes','Flooring','Reinforcement','Formwork','Road Works','Drainage','Water/Pipe Works','Other Civil Works'];
const $=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
let items=[];let editing=-1;
function init(){const sec=$('itemSection');sections.forEach(s=>sec.add(new Option(s,s)));$('itemSection').value='Earthwork';$('projectDate').value=new Date().toISOString().slice(0,10);$('measurementDate').value=new Date().toISOString().slice(0,10);$('addItem').addEventListener('click',saveItem);$('toggleWorksheet').addEventListener('click',toggleWorksheet);$('useCalculated').addEventListener('change',()=>{if($('useCalculated').checked&&Number.isFinite(calcQty()))$('itemQty').value=calcQty();});['mLength','mWidth','mHeight','mNumber','mFactor'].forEach(id=>$(id).addEventListener('input',updateWorksheet));$('resetBoq').addEventListener('click',resetWorkspace);$('printBoq').addEventListener('click',()=>window.print());render();}
function calcQty(){const vals=['mLength','mWidth','mHeight','mNumber','mFactor'].map(id=>Number($(id).value));const [l,w,h,num,f]=vals;return [l,w,h,num,f].every(Number.isFinite)&&l>=0&&w>=0&&h>=0&&num>=0&&f>=0?l*w*h*num*f:NaN}
function updateWorksheet(){const q=calcQty();$('calculatedQty').textContent=Number.isFinite(q)?fmt(q):'—';const vals=['mLength','mWidth','mHeight','mNumber','mFactor'].map(id=>$(id).value);$('quantityFormula').textContent=vals.some(v=>v!=='')?`${vals.map((v,i)=>v===''?'?':v).join(' × ')} = ${Number.isFinite(q)?fmt(q):'—'}`:'Enter dimensions to calculate.';if($('useCalculated').checked&&Number.isFinite(q))$('itemQty').value=q;}
function toggleWorksheet(){const body=$('worksheetBody');body.hidden=!body.hidden;$('toggleWorksheet').textContent=body.hidden?'Show worksheet':'Hide worksheet';}
function saveItem(){const no=$('itemNo').value.trim(),section=$('itemSection').value,desc=$('itemDescription').value.trim(),unit=$('itemUnit').value,qty=Number($('itemQty').value),rate=Number($('itemRate').value),remarks=$('itemRemarks').value.trim(),err=$('itemError');const errors=[];if(!no)errors.push('Item number is required.');if(!section)errors.push('Section is required.');if(!desc)errors.push('Work description is required.');if(!unit)errors.push('Unit is required.');if($('itemQty').value.trim()===''||!Number.isFinite(qty)||qty<0)errors.push('Enter a valid non-negative quantity.');if($('itemRate').value.trim()===''||!Number.isFinite(rate)||rate<0)errors.push('Enter a valid non-negative rate.');if(errors.length){err.textContent=errors.join(' ');err.hidden=false;return}err.hidden=true;const item={no,section,desc,unit,qty,rate,remarks,amount:qty*rate};if(editing>=0)items[editing]=item;else items.push(item);editing=-1;clearEditor();render();}
function clearEditor(){['itemNo','itemDescription','itemQty','itemRate','itemRemarks'].forEach(id=>$(id).value='');$('itemUnit').value='';$('itemSection').value='Earthwork';$('useCalculated').checked=false;['mLength','mWidth','mHeight'].forEach(id=>$(id).value='');$('mNumber').value='1';$('mFactor').value='1';$('itemError').hidden=true;updateWorksheet();}
function render(){const tbody=$('boqRows');tbody.innerHTML=items.map((x,i)=>`<tr><td>${esc(x.no)}</td><td>${esc(x.section)}</td><td>${esc(x.desc)}</td><td>${esc(x.unit)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${fmt(x.rate)}</td><td class="num">${fmt(x.amount)}</td><td>${esc(x.remarks)}</td><td><div class="row-actions"><button type="button" data-edit="${i}">Edit</button><button type="button" data-remove="${i}">Remove</button></div></td></tr>`).join('');$('emptyItems').hidden=items.length>0;tbody.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editItem(Number(b.dataset.edit))));tbody.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{items.splice(Number(b.dataset.remove),1);render()}));const total=items.reduce((a,x)=>a+x.amount,0);$('grandTotal').textContent=`NPR ${fmt(total)}`;renderSections();}
function renderSections(){const map={};items.forEach(x=>map[x.section]=(map[x.section]||0)+x.amount);const rows=Object.entries(map);$('sectionSummary').innerHTML=rows.length?rows.map(([s,n])=>`<div class="summary-row"><span>${esc(s)}</span><strong>NPR ${fmt(n)}</strong></div>`).join(''):'<p>No section totals yet.</p>';}
function editItem(i){const x=items[i];editing=i;$('itemNo').value=x.no;$('itemSection').value=x.section;$('itemDescription').value=x.desc;$('itemUnit').value=x.unit;$('itemQty').value=x.qty;$('itemRate').value=x.rate;$('itemRemarks').value=x.remarks;$('itemError').hidden=true;$('itemEditor').scrollIntoView({behavior:'smooth',block:'start'});}
function resetWorkspace(){if(!confirm('Reset the BOQ workspace and remove all entered items?'))return;items=[];editing=-1;document.querySelectorAll('input,textarea').forEach(el=>{if(!['mNumber','mFactor'].includes(el.id)&&el.type!=='date')el.value=''});$('projectDate').value=new Date().toISOString().slice(0,10);$('measurementDate').value=new Date().toISOString().slice(0,10);$('mNumber').value='1';$('mFactor').value='1';clearEditor();render();}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
document.addEventListener('DOMContentLoaded',init);
