const defaultSections=['Earthwork','Concrete','Reinforced Concrete','Masonry','Plaster & Finishes','Flooring','Reinforcement','Formwork','Road Works','Drainage','Water/Pipe Works','Other Civil Works'];
let sections=[...defaultSections],items=[],editing=-1,itemMode='idle';
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const esc=v=>String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function init(){populateSections();$('projectDate').value=today();$('measurementDate').value=today();$('addItem').addEventListener('click',handleAddItem);$('toggleWorksheet').addEventListener('click',toggleWorksheet);$('toggleSections').addEventListener('click',()=>{const x=$('sectionManager');x.hidden=!x.hidden;$('toggleSections').textContent=x.hidden?'Manage sections':'Hide section manager'});$('addSection').addEventListener('click',addSection);$('useCalculated').addEventListener('change',()=>{const q=calcQty();if($('useCalculated').checked&&Number.isFinite(q))$('itemQty').value=q});['mLength','mWidth','mHeight','mNumber','mFactor'].forEach(id=>$(id).addEventListener('input',updateWorksheet));$('resetBoq').addEventListener('click',resetWorkspace);$('printBoq').addEventListener('click',()=>window.print());$('itemSection').addEventListener('focus',()=>populateSections($('itemSection').value));renderCustomSections();render()}
function today(){return new Date().toISOString().slice(0,10)}
function populateSections(selected='Earthwork'){const sec=$('itemSection');if(!sec)return;const current=selected||sec.value||sections[0]||'';sec.replaceChildren(...sections.map(s=>{const option=document.createElement('option');option.value=s;option.textContent=s;return option}));if(sections.includes(current))sec.value=current;else if(sections.length)sec.value=sections[0]}
function addSection(){const input=$('newSection');if(!input)return;const name=input.value.trim();if(!name){input.focus();return}if(sections.some(s=>s.toLowerCase()===name.toLowerCase())){input.value='';populateSections(name);input.focus();return}sections.push(name);input.value='';renderCustomSections();populateSections(name);$('itemSection').focus()}
function startRenameSection(i){const old=sections[i];if(old==null)return;const chip=document.querySelector(`[data-section-index="${i}"]`);if(!chip)return;chip.innerHTML=`<input class="section-edit-input" type="text" value="${esc(old)}" aria-label="New section name"><button type="button" data-save-rename="${i}">Save</button><button type="button" data-cancel-rename="${i}">Cancel</button>`;const input=chip.querySelector('.section-edit-input');input.focus();input.select();const save=()=>{const name=input.value.trim();if(!name||name===old||sections.some((s,j)=>j!==i&&s.toLowerCase()===name.toLowerCase())){input.focus();return}sections[i]=name;items.forEach(x=>{if(x.section===old)x.section=name});renderCustomSections();populateSections(name);render()};chip.querySelector('[data-save-rename]').addEventListener('click',save);chip.querySelector('[data-cancel-rename]').addEventListener('click',renderCustomSections);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();save()}if(e.key==='Escape'){e.preventDefault();renderCustomSections()}})}
function renameSection(i){startRenameSection(i)}
function removeSection(i){const name=sections[i];if(items.some(x=>x.section===name)){alert('This section contains BOQ items. Move or remove those items before deleting the section.');return}if(!confirm(`Remove section “${name}”?`))return;sections.splice(i,1);populateSections();renderCustomSections()}
function renderCustomSections(){$('customSections').innerHTML=sections.map((s,i)=>`<span class="section-chip" data-section-index="${i}">${esc(s)}<button type="button" data-rename="${i}" aria-label="Rename ${esc(s)}">Rename</button>${defaultSections.includes(s)?'':'<button type="button" data-delete="'+i+'" aria-label="Delete '+esc(s)+'">×</button>'}</span>`).join('');$('customSections').querySelectorAll('[data-rename]').forEach(b=>b.addEventListener('click',()=>renameSection(Number(b.dataset.rename))));$('customSections').querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>removeSection(Number(b.dataset.delete))))}
function calcQty(){const vals=['mLength','mWidth','mHeight','mNumber','mFactor'].map(id=>Number($(id).value));const [l,w,h,num,f]=vals;return vals.every(Number.isFinite)&&l>=0&&w>=0&&h>=0&&num>=0&&f>=0?l*w*h*num*f:NaN}
function updateWorksheet(){const q=calcQty(),vals=['mLength','mWidth','mHeight','mNumber','mFactor'].map(id=>$(id).value);$('calculatedQty').textContent=Number.isFinite(q)?fmt(q):'—';$('quantityFormula').textContent=vals.some(v=>v!=='')?`${vals.map(v=>v===''?'?':v).join(' × ')} = ${Number.isFinite(q)?fmt(q):'—'}`:'Enter dimensions to calculate.';if($('useCalculated').checked&&Number.isFinite(q))$('itemQty').value=q}
function toggleWorksheet(){const body=$('worksheetBody');body.hidden=!body.hidden;$('toggleWorksheet').textContent=body.hidden?'Show worksheet':'Hide worksheet'}
function handleAddItem(){if(itemMode==='editing'||itemMode==='adding'){saveItem();return}clearEditor();itemMode='adding';editing=-1;const button=$('addItem');button.textContent='Save item';button.dataset.mode='save';button.setAttribute('aria-label','Save BOQ item');$('itemEditor').scrollIntoView({behavior:'smooth',block:'start'});$('itemNo').focus()}
function saveItem(){const no=$('itemNo').value.trim(),section=$('itemSection').value,desc=$('itemDescription').value.trim(),unit=$('itemUnit').value,qty=Number($('itemQty').value),rate=Number($('itemRate').value),remarks=$('itemRemarks').value.trim(),err=$('itemError'),errors=[];if(!no)errors.push('Item number is required.');if(!section)errors.push('Section is required.');if(!desc)errors.push('Work description is required.');if(!unit)errors.push('Unit is required.');if($('itemQty').value.trim()===''||!Number.isFinite(qty)||qty<0)errors.push('Enter a valid non-negative quantity.');if($('itemRate').value.trim()===''||!Number.isFinite(rate)||rate<0)errors.push('Enter a valid non-negative rate.');if(errors.length){err.textContent=errors.join(' ');err.hidden=false;return}err.hidden=true;const item={no,section,desc,unit,qty,rate,remarks,amount:qty*rate,rateAnalysis:{materials:[],labour:[],equipment:[],wastage:null,overhead:null,profit:null,other:[]},measurement:{note:'',location:'',drawingReference:'',date:'',measured:null,approved:null,previous:null,current:null}};if(editing>=0){const old=items[editing];item.rateAnalysis=old.rateAnalysis||item.rateAnalysis;item.measurement=old.measurement||item.measurement;items[editing]=item}else items.push(item);editing=-1;itemMode='idle';clearEditor();render()}
function clearEditor(){$('itemNo').value='';$('itemDescription').value='';$('itemQty').value='';$('itemRate').value='';$('itemRemarks').value='';$('itemUnit').value='';populateSections(sections[0]||'');$('useCalculated').checked=false;['mLength','mWidth','mHeight'].forEach(id=>$(id).value='');$('mNumber').value='1';$('mFactor').value='1';$('itemError').hidden=true;updateWorksheet();const button=$('addItem');button.textContent='+ Add item';button.dataset.mode='add';button.setAttribute('aria-label','Add BOQ item')}
function render(){const tbody=$('boqRows');tbody.innerHTML=items.map((x,i)=>`<tr><td>${esc(x.no)}</td><td>${esc(x.section)}</td><td>${esc(x.desc)}</td><td>${esc(x.unit)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${fmt(x.rate)}</td><td class="num">${fmt(x.amount)}</td><td>${esc(x.remarks)}</td><td><div class="row-actions"><button type="button" data-edit="${i}">Edit</button><button type="button" data-remove="${i}">Remove</button></div></td></tr>`).join('');$('emptyItems').hidden=items.length>0;tbody.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editItem(Number(b.dataset.edit))));tbody.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{items.splice(Number(b.dataset.remove),1);render()}));const total=items.reduce((a,x)=>a+x.amount,0);$('grandTotal').textContent=`NPR ${fmt(total)}`;renderSections()}
function renderSections(){const map={};items.forEach(x=>map[x.section]=(map[x.section]||0)+x.amount);const rows=Object.entries(map);$('sectionSummary').innerHTML=rows.length?rows.map(([s,n])=>`<div class="summary-row"><span>${esc(s)}</span><strong>NPR ${fmt(n)}</strong></div>`).join(''):'<p>No section totals yet.</p>'}
function editItem(i){const x=items[i];editing=i;itemMode='editing';populateSections(x.section);$('addItem').textContent='Save item';$('addItem').dataset.mode='save';$('addItem').setAttribute('aria-label','Save BOQ item');$('itemNo').value=x.no;$('itemSection').value=x.section;$('itemDescription').value=x.desc;$('itemUnit').value=x.unit;$('itemQty').value=x.qty;$('itemRate').value=x.rate;$('itemRemarks').value=x.remarks;$('itemError').hidden=true;$('itemEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function resetWorkspace(){if(!confirm('Reset the BOQ workspace and remove all entered items?'))return;items=[];editing=-1;itemMode='idle';document.querySelectorAll('input,textarea').forEach(el=>{if(!['mNumber','mFactor'].includes(el.id)&&el.type!=='date')el.value=''});$('projectDate').value=today();$('measurementDate').value=today();$('mNumber').value='1';$('mFactor').value='1';clearEditor();render()}
document.addEventListener('DOMContentLoaded',init);
