/* CivilKosh professional document output owner.
   The renderer consumes the existing BOQ, measurement, IPC and variation state.
   IPC remains a payment document; Detailed Measurement remains a separate record. */
(function(){
  'use strict';
  const escOut=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const fmtOut=v=>typeof fmt==='function'?fmt(num(v)):new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(num(v));
  const money=v=>`NPR ${fmtOut(v)}`;
  const val=id=>document.getElementById(id)?.value?.trim()||'';
  const hasFn=n=>typeof window[n]==='function';
  function projectData(){
    const p=hasFn('ipcProject')?ipcProject():{};
    return {name:val('projectName'),location:val('projectLocation'),client:val('projectClient'),contractor:val('projectContractor'),preparedBy:val('preparedBy'),date:val('projectDate'),ref:val('projectRef'),type:val('projectType'),workOrder:val('workOrder'),remarks:val('projectRemarks'),agreementNo:p.agreementNo||'',agreementDate:p.agreementDate||'',acceptedContractAmount:p.acceptedContractAmount,commencementDate:p.commencementDate||'',originalCompletionDate:p.originalCompletionDate||'',revisedCompletionDate:p.revisedCompletionDate||'',measurementBookNo:p.measurementBookNo||'',mbPage:p.mbPageReference||''};
  }
  function recordData(){return typeof ipcState!=='undefined'&&ipcState.record?ipcState.record:{};}
  function printWindow(title,body){const w=window.open('','_blank');if(!w){alert('Allow pop-ups to print the document.');return}w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escOut(title)}</title><style>${printCss()}</style></head><body>${body}</body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print()},160)}
  function printCss(){return `
    @page{size:A4 portrait;margin:14mm 12mm 15mm}*{box-sizing:border-box}html{-webkit-print-color-adjust:exact;print-color-adjust:exact}
    body{margin:0;background:#fff;color:#202522;font-family:Arial,Helvetica,sans-serif;font-size:8.8pt;line-height:1.34}.document{width:100%}h1,h2,h3,p{margin:0}
    .mast{border:1px solid #666d68;padding:8pt 9pt;margin-bottom:7pt;text-align:center}.mast h1{font-size:16pt;line-height:1.15;text-transform:uppercase;letter-spacing:.015em}.mast .subtitle{font-size:8.3pt;margin-top:3pt}.mast .docref{font-size:8pt;margin-top:4pt;font-weight:700}
    .meta{display:grid;grid-template-columns:1fr 1fr;border:1px solid #8a918c;margin-bottom:8pt}.meta-row{display:grid;grid-template-columns:43% 57%;padding:3.5pt 5pt;border-bottom:1px solid #c8ccc9;min-width:0}.meta-row:nth-last-child(-n+2){border-bottom:0}.meta-row strong{font-weight:700}.meta-row span{overflow-wrap:anywhere;min-width:0}
    .section{margin-top:9pt}.section-title{font-size:9.7pt;text-transform:uppercase;letter-spacing:.03em;border-left:3px solid #4e5551;border-bottom:1px solid #4e5551;padding:3pt 5pt;margin-bottom:5pt;break-after:avoid;page-break-after:avoid}.section-note{font-size:7.5pt;color:#555d58;margin-bottom:5pt}.callout{border:1px solid #a0a6a2;background:#f7f8f7;padding:5pt 6pt;margin:5pt 0;font-size:7.5pt}.table-wrap{width:100%;margin-bottom:6pt;overflow:visible}
    table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #7c837e;padding:3.5pt 4pt;vertical-align:top;overflow-wrap:anywhere}th{background:#edf0ee;font-weight:700;text-align:left}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}.num{text-align:right;white-space:nowrap;overflow-wrap:normal}.center{text-align:center}.nowrap{white-space:nowrap}.small{font-size:7pt;color:#5a625d}.grand-total td{font-weight:700;background:#e8ece9;border-top:1.5px solid #424944}.section-row td{font-weight:700;background:#f5f6f5}
    .summary td{padding:3.5pt 5pt}.summary td:first-child{width:68%}.summary td:last-child{width:32%;text-align:right;font-weight:600;white-space:nowrap}.summary .emph td{font-weight:700;background:#e8ece9;border-top:1.5px solid #4e5551}
    .qty-table{font-size:7.8pt}.qty-table th:nth-child(1){width:7%}.qty-table th:nth-child(2){width:31%}.qty-table th:nth-child(3){width:8%}.qty-table th:nth-child(4){width:11%}.qty-table th:nth-child(5){width:11%}.qty-table th:nth-child(6){width:11%}.qty-table th:nth-child(7){width:11%}.qty-table th:nth-child(8){width:10%}
    .amount-table{font-size:7.7pt}.amount-table th:nth-child(1){width:7%}.amount-table th:nth-child(2){width:29%}.amount-table th:nth-child(3){width:12%}.amount-table th:nth-child(4){width:14%}.amount-table th:nth-child(5){width:14%}.amount-table th:nth-child(6){width:14%}.amount-table th:nth-child(7){width:10%}
    .evidence-group{border:1px solid #8a918c;margin:6pt 0 8pt;break-inside:avoid;page-break-inside:avoid}.evidence-head{display:grid;grid-template-columns:10% 34% 18% 18% 20%;background:#edf0ee;border-bottom:1px solid #8a918c}.evidence-head>div{padding:4pt 5pt;border-right:1px solid #8a918c}.evidence-head>div:last-child{border-right:0}.evidence-head strong{display:block;font-size:6.8pt;text-transform:uppercase;color:#58605b}.evidence-head span{display:block;margin-top:1pt}.evidence-record-table{font-size:7.2pt}.evidence-record-table th:nth-child(1){width:9%}.evidence-record-table th:nth-child(2){width:11%}.evidence-record-table th:nth-child(3){width:23%}.evidence-record-table th:nth-child(4){width:20%}.evidence-record-table th:nth-child(5){width:11%}.evidence-record-table th:nth-child(6){width:11%}.evidence-record-table th:nth-child(7){width:15%}.evidence-empty{padding:5pt;color:#5a625d;font-size:7.3pt}
    .variation-table,.docs-table{font-size:7.4pt}.variation-table th:nth-child(1){width:8%}.variation-table th:nth-child(2){width:16%}.variation-table th:nth-child(3){width:11%}.variation-table th:nth-child(4){width:10%}.variation-table th:nth-child(5){width:11%}.variation-table th:nth-child(6){width:16%}.variation-table th:nth-child(7){width:28%}.docs-table th:nth-child(1){width:34%}.docs-table th:nth-child(2){width:17%}.docs-table th:nth-child(3){width:22%}.docs-table th:nth-child(4){width:27%}
    .attachment-table{font-size:7.6pt}.attachment-table th:nth-child(1){width:8%}.attachment-table th:nth-child(2){width:42%}.attachment-table th:nth-child(3){width:18%}.attachment-table th:nth-child(4){width:32%}
    .signatures{display:grid;grid-template-columns:repeat(4,1fr);gap:12pt;margin-top:18pt;break-inside:avoid;page-break-inside:avoid}.sig{min-height:34pt;border-top:1px solid #555;padding-top:3pt;text-align:center;font-size:7pt}.footer{margin-top:8pt;border-top:1px solid #aeb4b0;padding-top:3pt;font-size:6.5pt;color:#58605b;display:flex;justify-content:space-between;gap:10pt}
    .boq-main th:nth-child(1){width:8%}.boq-main th:nth-child(2){width:39%}.boq-main th:nth-child(3){width:8%}.boq-main th:nth-child(4){width:12%}.boq-main th:nth-child(5){width:15%}.boq-main th:nth-child(6){width:18%}
    .measure-record{border:1px solid #7c837e;margin-bottom:7pt;break-inside:avoid;page-break-inside:avoid}.measure-record-head{display:grid;grid-template-columns:10% 14% 11% 30% 35%;background:#edf0ee;border-bottom:1px solid #7c837e}.measure-record-head>div{padding:3.5pt 4pt;border-right:1px solid #7c837e}.measure-record-head>div:last-child{border-right:0}.measure-record-head strong{display:block;font-size:6.7pt;color:#58605b;text-transform:uppercase}.measure-record-head span{display:block;overflow-wrap:anywhere}.measure-record-qty{display:grid;grid-template-columns:repeat(3,1fr);border-bottom:1px solid #7c837e}.measure-record-qty>div{padding:3.5pt 4pt;border-right:1px solid #7c837e;text-align:right}.measure-record-qty>div:last-child{border-right:0}.measure-record-qty strong{display:block;font-size:6.7pt;color:#58605b;text-align:left}.measure-record-qty span{font-weight:700}.measure-detail-title{font-weight:700;text-transform:uppercase;font-size:7.2pt;margin-bottom:3pt}.measure-detail-table{font-size:7.1pt}.measure-detail-table th,.measure-detail-table td{padding:3pt 3.5pt}.measure-detail-table th:nth-child(1){width:15%}.measure-detail-table th:nth-child(2){width:22%}.measure-detail-table th:nth-child(3){width:7%}.measure-detail-table th:nth-child(4){width:7%}.measure-detail-table th:nth-child(5){width:7%}.measure-detail-table th:nth-child(6){width:6%}.measure-detail-table th:nth-child(7){width:7%}.measure-detail-table th:nth-child(8){width:21%}.measure-detail-table th:nth-child(9){width:8%}.measure-breakdown-note{font-size:7pt;margin-top:3pt;padding-top:3pt;border-top:1px dotted #b9bfbb}
    @media screen{.table-wrap{overflow-x:auto}.amount-table{min-width:720px}}
  `;}
  function metaHtml(p,extra){const pairs=[['Project / Work',p.name],['Location',p.location],['Employer / Client',p.client],['Contractor',p.contractor],['Prepared By',p.preparedBy],['Document Date',p.date],['Project / Reference No.',p.ref],['Work Order / Contract No.',p.workOrder],['Agreement / Contract No.',p.agreementNo],['Agreement Date',p.agreementDate],['Accepted Contract Amount',p.acceptedContractAmount!==''&&p.acceptedContractAmount!=null?money(p.acceptedContractAmount):''],['Commencement Date',p.commencementDate],['Original Completion Date',p.originalCompletionDate],['Extension / Revised Completion Date',p.revisedCompletionDate],['Measurement Book No.',p.measurementBookNo],['MB Page / Reference',p.mbPage],...(extra||[])].filter(([,v])=>v!==''&&v!=null);return `<div class="meta">${pairs.map(([k,v])=>`<div class="meta-row"><strong>${escOut(k)}</strong><span>${escOut(v)}</span></div>`).join('')}</div>`}
  function mast(title,p,ref){return `<div class="mast"><h1>${escOut(title)}</h1><div class="subtitle">${escOut(p.name||'CivilKosh Project')}${p.location?` · ${escOut(p.location)}`:''}</div>${ref?`<div class="docref">${escOut(ref)}</div>`:''}</div>`}
  function footer(p,label){return `<div class="footer"><span>CivilKosh · ${escOut(label)}</span><span>${escOut(p.name||'Project')}</span></div>`}
  function boqGroups(){const map=new Map();items.forEach(item=>{const key=item.section||'Unsectioned';if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return [...map.entries()].map(([section,group])=>({section,items:group,total:group.reduce((s,x)=>s+num(x.qty)*num(x.rate),0)}))}
  function printBOQ(){const p=projectData(),groups=boqGroups(),total=items.reduce((s,x)=>s+num(x.qty)*num(x.rate),0);let rows='';groups.forEach(g=>{rows+=`<tr class="section-row"><td colspan="6">${escOut(g.section)} <span class="small">· Section subtotal ${money(g.total)}</span></td></tr>`;g.items.forEach(x=>{rows+=`<tr><td>${escOut(x.no)}</td><td>${escOut(x.desc)}${x.drawingReference?`<div class="small">Ref: ${escOut(x.drawingReference)}</div>`:''}</td><td class="center nowrap">${escOut(x.unit)}</td><td class="num">${fmtOut(x.qty)}</td><td class="num">${money(x.rate)}</td><td class="num">${money(num(x.qty)*num(x.rate))}</td></tr>`})});const body=`<div class="document">${mast('Bill of Quantities',p,p.workOrder||p.ref)}${metaHtml(p)}<section class="section"><h2 class="section-title">1. BOQ Abstract</h2><div class="table-wrap"><table><thead><tr><th>Section</th><th>Description / Work Group</th><th class="num">Amount</th></tr></thead><tbody>${groups.map((g,i)=>`<tr><td class="center">${i+1}</td><td>${escOut(g.section)}</td><td class="num">${money(g.total)}</td></tr>`).join('')}<tr class="grand-total"><td colspan="2">Grand Total</td><td class="num">${money(total)}</td></tr></tbody></table></div></section><section class="section"><h2 class="section-title">2. Detailed BOQ</h2><div class="table-wrap"><table class="boq-main"><thead><tr><th>Item</th><th>Description / Specification / Reference</th><th>Unit</th><th class="num">BOQ Qty</th><th class="num">Rate (NPR)</th><th class="num">Amount (NPR)</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No BOQ items are available.</td></tr>'}<tr class="grand-total"><td colspan="5">Grand Total</td><td class="num">${money(total)}</td></tr></tbody></table></div></section><section class="section"><h2 class="section-title">3. Measurement / Payment Basis</h2><div class="callout">The BOQ is the quantity-and-rate baseline. Actual payment quantities remain subject to the contract, drawings, specifications and verified site measurement.</div></section><div class="signatures"><div class="sig">Prepared By<br>${escOut(p.preparedBy||'')}</div><div class="sig">Checked By</div><div class="sig">Approved By</div><div class="sig">Contractor / Representative</div></div>${footer(p,'BOQ Document')}</div>`;printWindow(`BOQ — ${p.name||'CivilKosh'}`,body)}
  function measurementRecords(){const out=[];items.forEach(item=>(item.measurementRecords||[]).forEach((m,index)=>out.push({item,m,index})));return out}
  function measurementCalculation(b){const d=b?.detail||{};if(d.calculation&&String(d.calculation).trim())return String(d.calculation).trim();const type=d.type||'General / L×W×H',l=b.length===''?'—':b.length,w=b.width===''?'—':b.width,h=b.height===''?'—':b.height,n=b.number==null?'1':b.number,f=b.factor==null?'1':b.factor,q=b.quantity==null?'—':fmtOut(b.quantity);if(type==='Linear / Chainage'||type==='Pipe / Drainage')return `L ${l} × No. ${n} × Factor ${f} = ${q}`;if(type==='Area / Surface')return `L ${l} × W ${w} × No. ${n} × Factor ${f} = ${q}`;if(type==='Reinforcement / BBS')return `Dia ${d.diameter||'—'} mm × ${n} bars × Cut ${d.cutLength||'—'} m · Total length ${d.totalLength||'—'} m · Unit wt ${d.unitWeight||'—'} kg/m · Total wt ${d.totalWeight||'—'} kg = ${q}`;return `L ${l} × W ${w} × H/D ${h} × No. ${n} × Factor ${f} = ${q}`}
  function measurementBreakdownHtml(b){const d=b?.detail||{},type=d.type||'General / L×W×H',isRebar=type==='Reinforcement / BBS',element=[d.element,d.memberId].filter(Boolean).join(' · ')||'—',q=b.quantity==null?'—':fmtOut(b.quantity),calc=measurementCalculation(b);let table;if(isRebar)table=`<table class="measure-detail-table"><thead><tr><th>Type</th><th>Element / Member ID</th><th>Dia</th><th>Spacing</th><th>No.</th><th>Cut Length</th><th>Total Length</th><th>Total Weight</th><th>Qty</th></tr></thead><tbody><tr><td>${escOut(type)}</td><td>${escOut(element)}</td><td class="center">${escOut(d.diameter||'—')}</td><td class="center">${escOut(d.spacing||'—')}</td><td class="center">${escOut(b.number??'—')}</td><td class="center">${escOut(d.cutLength||'—')}</td><td class="center">${escOut(d.totalLength||'—')}</td><td class="num">${escOut(d.totalWeight||'—')}</td><td class="num">${escOut(q)}</td></tr></tbody></table>`;else table=`<table class="measure-detail-table"><thead><tr><th>Type</th><th>Element / Member ID</th><th>L</th><th>W</th><th>H / D / T</th><th>No.</th><th>Factor</th><th>Calculation</th><th>Qty</th></tr></thead><tbody><tr><td>${escOut(type)}</td><td>${escOut(element)}</td><td class="num">${escOut(b.length===''?'—':b.length)}</td><td class="num">${escOut(b.width===''?'—':b.width)}</td><td class="num">${escOut(b.height===''?'—':b.height)}</td><td class="num">${escOut(b.number??'—')}</td><td class="num">${escOut(b.factor??'—')}</td><td>${escOut(calc)}</td><td class="num">${escOut(q)}</td></tr></tbody></table>`;const notes=[d.barMark&&`Bar Mark: ${d.barMark}`,d.barType&&`Bar Type / Shape: ${d.barType}`,d.deduction&&`Deduction: ${d.deduction}`,d.addition&&`Addition: ${d.addition}`,b.note].filter(Boolean);return `<div><div class="measure-detail-title">Detailed Measurement</div>${table}${notes.length?`<div class="measure-breakdown-note"><strong>Remarks:</strong> ${escOut(notes.join(' · '))}</div>`:''}</div>`}
  function printMeasurement(){const p=projectData(),records=measurementRecords();const html=records.map(({item,m,index})=>{const bs=Array.isArray(m.breakdowns)?m.breakdowns:[];return `<section class="measure-record"><div class="measure-record-head"><div><strong>BOQ Item</strong><span>${escOut(item.no)}</span></div><div><strong>Record No.</strong><span>${index+1}</span></div><div><strong>Date</strong><span>${escOut(m.date||'—')}</span></div><div><strong>Location / Element</strong><span>${escOut(m.location||'—')}</span></div><div><strong>Drawing / Reference</strong><span>${escOut(m.drawingReference||'—')}</span></div></div><div class="measure-record-qty"><div><strong>Measured</strong><span>${m.measured==null?'—':fmtOut(m.measured)} ${escOut(item.unit)}</span></div><div><strong>Approved</strong><span>${m.approved==null?'—':fmtOut(m.approved)} ${escOut(item.unit)}</span></div><div><strong>Current / Claim</strong><span>${m.current==null?'—':fmtOut(m.current)} ${escOut(item.unit)}</span></div></div><div style="padding:4pt;border-bottom:1px solid #7c837e"><strong>Description:</strong> ${escOut(item.desc)}${m.remarks||m.note?`<br><strong>Remarks:</strong> ${escOut([m.remarks,m.note].filter(Boolean).join(' · '))}`:''}</div><div class="detail-body">${bs.length?bs.map(measurementBreakdownHtml).join(''):'<div class="detail-empty">No detailed measurement breakdown is saved for this record.</div>'}</div></section>`}).join('');const body=`<div class="document">${mast('Detailed Measurement Sheet / Measurement Book',p,p.workOrder||p.ref)}${metaHtml(p)}<section class="section"><h2 class="section-title">1. Measurement Records</h2>${html||'<div class="callout">No saved measurement records are available.</div>'}</section><div class="signatures"><div class="sig">Measured / Prepared By</div><div class="sig">Checked By</div><div class="sig">Verified / Approved By</div><div class="sig">Contractor / Representative</div></div>${footer(p,'Detailed Measurement Package')}</div>`;printWindow(`Measurement — ${p.name||'CivilKosh'}`,body)}
  function ipcRows(){if(!hasFn('ipcTotals'))return[];return ipcTotals().map((row,i)=>({row,item:items[row.itemIndex],index:i})).filter(x=>x.item)}
  function variationRows(){return items.map((item,index)=>({item,index,change:hasFn('variationData')?variationData(item):item.change||{}})).filter(x=>x.change&&x.change.classification&&x.change.classification!=='Original BOQ Item')}
  function ipcSavedEvidence(item,row,r){const saved=Array.isArray(r?.items)?r.items.find(x=>x.itemIndex===row.itemIndex):null;return Array.isArray(saved?.evidence)?saved.evidence.filter((i,pos,a)=>Number.isInteger(i)&&i>=0&&i<(item.measurementRecords||[]).length&&a.indexOf(i)===pos):[]}
  function ipcEvidenceRecords(rows,r){const out=[];rows.filter(x=>num(x.row.current)>0).forEach(x=>ipcSavedEvidence(x.item,x.row,r).forEach(i=>{const m=x.item.measurementRecords?.[i];if(m)out.push({item:x.item,row:x.row,record:i+1,m,index:i})}));return out}
  function ipcEvidenceGroups(rows,r){const groups=[];rows.filter(x=>num(x.row.current)>0).forEach(x=>{const refs=ipcSavedEvidence(x.item,x.row,r);const records=refs.map(i=>x.item.measurementRecords?.[i]).filter(Boolean);const measured=records.reduce((s,m)=>s+num(m.measured),0);const approved=records.reduce((s,m)=>s+(m.approved==null?0:num(m.approved)),0);groups.push({item:x.item,row:x.row,refs,records,measured,approved})});return groups}
  function docsRows(){
    const r=recordData(),raw=Array.isArray(r.supportingDocuments)?r.supportingDocuments:[];
    const docs=hasFn('ipcNormalizeDocuments')?ipcNormalizeDocuments(raw):raw;
    const defaults=typeof ipcDocumentNames!=='undefined'&&Array.isArray(ipcDocumentNames)?ipcDocumentNames:['Measurement Book / Measurement Sheet','Joint Measurement Record','Approved Drawing / Reference','Site Measurement Evidence','Laboratory / Test Report','VAT Bill / Invoice','Other Supporting Document'];
    return docs.filter((d,i)=>{
      const name=String(d?.name||'').trim(),status=String(d?.status||'').trim(),reference=String(d?.reference||'').trim(),date=String(d?.date||'').trim(),remarks=String(d?.remarks||d?.note||'').trim();
      const customName=Boolean(name&&name!==(defaults[i]||''));
      const applicable=status==='Available'||status==='Pending';
      return applicable||Boolean(reference||date||remarks||customName);
    });
  }
  function printIPC(no){
    if(no&&hasFn('ipcEdit'))ipcEdit(no);
    const p=projectData(),r=recordData(),rows=ipcRows(),summary=hasFn('ipcSummary')?ipcSummary(rows.map(x=>x.row)):{previous:0,current:0,cumulative:0,balance:0};
    const retention=num(r.retention),advance=num(r.advance),deduction=num(r.deduction),addition=num(r.addition),net=summary.current-retention-advance-deduction+addition;
    const amountWords=hasFn('ipcAmountWords')?ipcAmountWords(net):`NPR ${fmtOut(net)}`,variation=variationRows(),evidenceGroups=ipcEvidenceGroups(rows,r),evidenceRecords=ipcEvidenceRecords(rows,r),docs=docsRows();
    const status=r.editingNo?'Saved IPC':'UNSAVED DRAFT';
    const quantityRows=rows.map(x=>{const q=x.row;return `<tr><td>${escOut(x.item.no)}</td><td>${escOut(x.item.desc)}${x.item.drawingReference?`<div class="small">Ref: ${escOut(x.item.drawingReference)}</div>`:''}</td><td class="center nowrap">${escOut(x.item.unit)}</td><td class="num">${fmtOut(x.item.qty)}</td><td class="num">${fmtOut(q.previous)}</td><td class="num">${fmtOut(q.current)}</td><td class="num">${fmtOut(q.cumulative)}</td><td class="num">${fmtOut(q.balanceQty)}</td></tr>`}).join('');
    const amountRows=rows.map(x=>{const q=x.row;return `<tr><td>${escOut(x.item.no)}</td><td>${escOut(x.item.desc)}</td><td class="num">${money(x.item.rate)}</td><td class="num">${money(q.previousAmount)}</td><td class="num">${money(q.currentAmount)}</td><td class="num">${money(q.cumulativeAmount)}</td><td class="num">${money(q.balanceAmount)}</td></tr>`}).join('');
    const evidenceHtml=evidenceGroups.filter(g=>g.records.length).map(g=>{const item=g.item,q=g.row;const recordRows=g.records.map((m,idx)=>{const originalIndex=g.refs[idx];const note=m.remarks||m.note||'Saved measurement record';return `<tr><td class="center">Record ${originalIndex+1}</td><td>${escOut(m.date||'—')}</td><td>${escOut(m.location||'—')}</td><td>${escOut(m.drawingReference||'—')}</td><td class="num">${m.measured==null?'—':fmtOut(m.measured)} ${escOut(item.unit)}</td><td class="num">${m.approved==null?'—':fmtOut(m.approved)+' '+item.unit}</td><td>${escOut(note)}</td></tr>`}).join('');return `<section class="evidence-group"><div class="evidence-head"><div><strong>BOQ Item</strong><span>${escOut(item.no)}</span></div><div><strong>Description</strong><span>${escOut(item.desc)}</span></div><div><strong>Unit</strong><span>${escOut(item.unit)}</span></div><div><strong>Current IPC Qty</strong><span>${fmtOut(q.current)} ${escOut(item.unit)}</span></div><div><strong>Measurement References</strong><span>${g.refs.map(i=>`Record ${i+1}`).join(', ')}</span></div></div><div class="table-wrap"><table class="evidence-record-table"><thead><tr><th>Record Ref</th><th>Date</th><th>Location / Grid / Chainage</th><th>Drawing / MB Reference</th><th class="num">Measured Qty</th><th class="num">Approved Qty</th><th>Verification Note</th></tr></thead><tbody>${recordRows}</tbody></table></div></section>`}).join('');
    const variationHtml=variation.map(v=>`<tr><td>${escOut(v.item.no)}</td><td>${escOut(v.change.classification)}</td><td>${escOut(v.change.referenceNo||'—')}</td><td>${escOut(v.change.status||'—')}</td><td class="num">${v.change.revisedQuantity===''?'—':fmtOut(v.change.revisedQuantity)}</td><td>${escOut(v.change.approvalReference||'—')}</td><td>${escOut(v.change.reason||v.change.remarks||'—')}</td></tr>`).join('');
    const docsHtml=docs.map(d=>`<tr><td>${escOut(d.name||'Supporting Document')}</td><td>${escOut(d.status||'—')}</td><td>${escOut(d.reference||'—')}</td><td>${escOut([d.date,d.remarks||d.note].filter(Boolean).join(' · ')||'—')}</td></tr>`).join('');
    const hasAdjustments=retention!==0||advance!==0||deduction!==0||addition!==0||String(r.adjustmentNote||'').trim()!=='';
    let sectionNo=1;
    const section=(title,content)=>`<section class="section"><h2 class="section-title">${sectionNo++}. ${title}</h2>${content}</section>`;
    const identificationSection=section('IPC Identification / Project & Contract Information','<p class="section-note">The identification and contract particulars above form the document control record for this certificate.</p>');
    const paymentSection=section('Payment Summary',`<div class="table-wrap"><table class="summary"><tbody><tr><td>Previous Certified Gross Amount</td><td>${money(summary.previous)}</td></tr><tr><td>Current IPC Gross Amount</td><td>${money(summary.current)}</td></tr><tr><td>Cumulative Certified Gross Amount</td><td>${money(summary.cumulative)}</td></tr><tr><td>Balance BOQ Value</td><td>${money(summary.balance)}</td></tr>${hasAdjustments?`<tr><td>Retention</td><td>− ${money(retention)}</td></tr><tr><td>Advance Recovery</td><td>− ${money(advance)}</td></tr><tr><td>Other Deduction</td><td>− ${money(deduction)}</td></tr><tr><td>Other Addition / Adjustment</td><td>+ ${money(addition)}</td></tr>`:''}<tr class="emph"><td>Current Net Payable</td><td>${money(net)}</td></tr><tr><td>Amount in Words</td><td>${escOut(amountWords)}</td></tr></tbody></table></div>`);
    const boqSection=section('BOQ Current Bill / Valuation',`<p class="section-note">This is the primary payment-control section. Quantities are certified at BOQ-item level; financial values are derived from the saved BOQ rate.</p><div class="table-wrap"><table class="qty-table"><thead><tr><th>Item</th><th>Description</th><th>Unit</th><th class="num">BOQ Qty</th><th class="num">Previous Qty</th><th class="num">Current Qty</th><th class="num">Cumulative Qty</th><th class="num">Balance Qty</th></tr></thead><tbody>${quantityRows||'<tr><td colspan="8">No BOQ items are available.</td></tr>'}</tbody></table></div><div class="table-wrap"><table class="amount-table"><thead><tr><th>Item</th><th>Description</th><th class="num">Rate</th><th class="num">Previous Amount</th><th class="num">Current Amount</th><th class="num">Cumulative Amount</th><th class="num">Balance Amount</th></tr></thead><tbody>${amountRows||'<tr><td colspan="7">No financial rows are available.</td></tr>'}<tr class="grand-total"><td colspan="3">Totals</td><td class="num">${money(summary.previous)}</td><td class="num">${money(summary.current)}</td><td class="num">${money(summary.cumulative)}</td><td class="num">${money(summary.balance)}</td></tr></tbody></table></div>`);
    const evidenceSection=section('Measurement / MB Verification',evidenceHtml||'<p class="section-note">No measurement record is linked to the current IPC quantities.</p>');
    const variationSection=variation.length?section('Variation / Extra / Substituted Work',`<div class="table-wrap"><table class="variation-table"><thead><tr><th>Item</th><th>Classification</th><th>Reference</th><th>Status</th><th class="num">Revised Qty</th><th>Approval / Instruction</th><th>Reason / Remarks</th></tr></thead><tbody>${variationHtml}</tbody></table></div>`):'';
    const adjustmentSection=hasAdjustments?section('Deductions / Adjustments',`<div class="table-wrap"><table class="summary"><tbody><tr><td>Retention</td><td>− ${money(retention)}</td></tr><tr><td>Advance Recovery</td><td>− ${money(advance)}</td></tr><tr><td>Other Deduction</td><td>− ${money(deduction)}</td></tr><tr><td>Other Addition / Adjustment</td><td>+ ${money(addition)}</td></tr><tr><td>Basis / Note</td><td>${escOut(r.adjustmentNote||'—')}</td></tr></tbody></table></div>`):'';
    const certificationSection=section('Net Payment / Certification',`<div class="table-wrap"><table class="summary"><tbody><tr class="emph"><td>Current Net Payable</td><td>${money(net)}</td></tr><tr><td>Amount in Words</td><td>${escOut(amountWords)}</td></tr><tr><td>Prepared By</td><td>${escOut(r.certification?.preparedBy||p.preparedBy||'—')}</td></tr><tr><td>Checked By</td><td>${escOut(r.certification?.checkedBy||'—')}</td></tr><tr><td>Recommended By</td><td>${escOut(r.certification?.recommendedBy||'—')}</td></tr><tr><td>Approved By</td><td>${escOut(r.certification?.approvedBy||'—')}</td></tr><tr><td>Designation</td><td>${escOut(r.certification?.designation||'—')}</td></tr><tr><td>Certification / Approval Date</td><td>${escOut(r.certification?.date||'—')}</td></tr><tr><td>Reference / Note</td><td>${escOut(r.certification?.note||'—')}</td></tr></tbody></table></div>`);
    const docsSection=docs.length?section('Supporting Documents / Attachment Register',`<div class="table-wrap"><table class="docs-table"><thead><tr><th>Document / Evidence</th><th>Status</th><th>Reference / Document No.</th><th>Date / Remarks</th></tr></thead><tbody>${docsHtml}</tbody></table></div>`):'';
    const indexRows=[];
    evidenceRecords.forEach((e,i)=>{const source=[e.m.date,e.m.drawingReference||e.m.location].filter(Boolean).join(' · ');indexRows.push(`<tr><td>E-${String(i+1).padStart(2,'0')}</td><td>Measurement Record ${e.record} — BOQ Item ${escOut(e.item.no)}</td><td>Saved</td><td>${escOut(source||'Measurement / MB record')}</td></tr>`)});
    docs.forEach((d,i)=>{const source=[d.reference,d.date,d.remarks||d.note].filter(Boolean).join(' · ');indexRows.push(`<tr><td>D-${String(i+1).padStart(2,'0')}</td><td>${escOut(d.name||'Supporting Document')}</td><td>${escOut(d.status||'Saved')}</td><td>${escOut(source||'Saved supporting document')}</td></tr>`)});
    const attachmentSection=indexRows.length?section('Evidence Index',`<div class="table-wrap"><table class="attachment-table"><thead><tr><th>Ref.</th><th>Attachment / Evidence</th><th>Status</th><th>Source / Notes</th></tr></thead><tbody>${indexRows.join('')}</tbody></table></div>`):'';
    const body=`<div class="document">${mast('Interim Payment Certificate / Running Bill',p,r.no||no||'')}${metaHtml(p,[['IPC Status',status],['IPC / Running Bill No.',r.no||no||'—'],['Bill Date',r.date||p.date||'—'],['Billing / Measurement Period',r.period||'—'],['Previous IPC',r.previousIpcNo||'—']])}${identificationSection}${paymentSection}${boqSection}${evidenceSection}${variationSection}${adjustmentSection}${certificationSection}${docsSection}${attachmentSection}${footer(p,`IPC ${r.no||no||''} · Interim Payment Certificate`)}</div>`;
    printWindow(`IPC ${r.no||no||''} — ${p.name||'CivilKosh'}`,body);
  }
  function installOutputControls(){
    const boq=document.getElementById('printBoq');if(boq&&!boq.dataset.documentOutputBound){boq.dataset.documentOutputBound='1';boq.addEventListener('click',e=>{e.preventDefault();printBOQ()})}
    const save=document.getElementById('saveMeasurement');if(save&&!document.getElementById('printMeasurementPackage')){const b=document.createElement('button');b.type='button';b.id='printMeasurementPackage';b.className='secondary-btn';b.textContent='Print Measurement Package';b.addEventListener('click',()=>printMeasurement());save.parentElement?.appendChild(b)}
    if(!document.documentElement.dataset.ipcOutputDelegated){document.documentElement.dataset.ipcOutputDelegated='1';document.addEventListener('click',function(e){const b=e.target.closest?.('#printIpc,[data-ipc-print]');if(!b)return;e.preventDefault();const no=b.getAttribute('data-ipc-print')||'';printIPC(no)},true)}
    window.printBOQ=printBOQ;window.printMeasurement=printMeasurement;window.printIPC=printIPC;window.printIpc=printIPC;
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installOutputControls);else installOutputControls();
})();