/* CivilKosh real XLSX export. Reads the existing project state; does not create a second data model. */
(function(){
  'use strict';
  if(window.__civilKoshExcelExportInstalled)return;
  window.__civilKoshExcelExportInstalled=true;
  const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
  const s=v=>v==null?'':String(v);
  const date=v=>{const x=s(v);if(!x)return null;const m=x.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):x};
  const itemsW=()=>Array.isArray(window.items)?window.items:[];
  const fmtMoney='"NPR "#,##0.00';
  const fmtQty='#,##0.00';
  const fmtPct='0.00%';
  function project(){
    const val=id=>document.getElementById(id)?.value?.trim()||'';
    const ipc=window.ipcState?.record||{};
    const c=ipc.contract&&typeof ipc.contract==='object'?ipc.contract:(window.ipcState?.project||{});
    return {name:val('projectName'),location:val('projectLocation'),client:val('projectClient'),contractor:val('projectContractor'),preparedBy:val('preparedBy'),date:val('projectDate'),ref:val('projectRef'),type:val('projectType'),workOrder:val('workOrder'),remarks:val('projectRemarks'),agreementNo:c.agreementNo||'',agreementDate:c.agreementDate||'',acceptedContractAmount:n(c.acceptedContractAmount),commencementDate:c.commencementDate||'',originalCompletionDate:c.originalCompletionDate||'',revisedCompletionDate:c.revisedCompletionDate||'',measurementBookNo:c.measurementBookNo||'',mbPage:c.mbPageReference||''};
  }
  function quantity(item,index){
    const rec=(item.ipcRecords||[]).filter(r=>r&&r.no).slice().sort((a,b)=>(typeof ipcOrdinal==='function'?ipcOrdinal(a.no):0)-(typeof ipcOrdinal==='function'?ipcOrdinal(b.no):0));
    let previous=0,current=0;const active=window.ipcState?.record;
    if(active?.editingNo){previous=typeof ipcPrevQty==='function'?n(ipcPrevQty(item,active.editingNo))||0:rec.filter(r=>(typeof ipcOrdinal==='function'?ipcOrdinal(r.no):0)<(typeof ipcOrdinal==='function'?ipcOrdinal(active.editingNo):0)).reduce((a,r)=>a+(n(r.items?.find(x=>x.itemIndex===index)?.current)||0),0);current=n(active.items?.find(x=>x.itemIndex===index)?.current)||0}
    else if(rec.length){const last=rec[rec.length-1];current=n(last.items?.find(x=>x.itemIndex===index)?.current)||0;previous=rec.slice(0,-1).reduce((a,r)=>a+(n(r.items?.find(x=>x.itemIndex===index)?.current)||0),0)}
    const cumulative=previous+current;const allowed=typeof variationAllowedQty==='function'?n(variationAllowedQty(item))??0:n(item.qty)||0;
    return {previous,current,cumulative,balance:allowed-cumulative,allowed,progress:allowed>0?cumulative/allowed:null,rate:n(item.rate)||0,currentAmount:current*(n(item.rate)||0),cumulativeAmount:cumulative*(n(item.rate)||0)};
  }
  function baseRows(p){return [['Project Name',p.name],['Location',p.location],['Employer / Client',p.client],['Contractor',p.contractor],['Prepared By',p.preparedBy],['Project Date',date(p.date)],['Project / Reference No.',p.ref],['Project Type',p.type],['Work Order / Contract No.',p.workOrder],['Agreement / Contract No.',p.agreementNo],['Agreement Date',date(p.agreementDate)],['Accepted Contract Amount',p.acceptedContractAmount],['Commencement Date',date(p.commencementDate)],['Original Completion Date',date(p.originalCompletionDate)],['Extension / Revised Completion Date',date(p.revisedCompletionDate)],['Measurement Book No.',p.measurementBookNo],['MB Page / Reference',p.mbPage]].filter(x=>x[1]!==''&&x[1]!==null);}
  function sheet(wb,name,title,headers,rows,projectRows){
    const aoa=[[title],...baseRows(projectRows||project()),[],headers,...rows];
    const ws=XLSX.utils.aoa_to_sheet(aoa);const headerRow=baseRows(projectRows||project()).length+3;const lastRow=headerRow+rows.length;const lastCol=headers.length-1;
    ws['!freeze']={xSplit:0,ySplit:headerRow};
    ws['!autofilter']={ref:XLSX.utils.encode_range({s:{r:headerRow,c:0},e:{r:lastRow,c:lastCol}})};
    ws['!cols']=headers.map(h=>({wch:Math.max(12,Math.min(38,h.length+4))}));
    ws['!cols'][0]={wch:16};
    headers.forEach((h,c)=>{const cell=ws[XLSX.utils.encode_cell({r:headerRow,c})];if(cell){cell.s={font:{bold:true},fill:{fgColor:{rgb:'E7ECE9'}},alignment:{vertical:'center',wrapText:true}}}});
    for(let r=headerRow+1;r<=lastRow;r++)for(let c=0;c<=lastCol;c++){const cell=ws[XLSX.utils.encode_cell({r,c})];if(!cell)continue;cell.s=cell.s||{};cell.s.alignment={vertical:'top',wrapText:c===1||headers[c].toLowerCase().includes('description')||headers[c].toLowerCase().includes('remarks')||headers[c].toLowerCase().includes('details')};}
    ws['A1'].s={font:{bold:true,sz:16},alignment:{vertical:'center'}};
    wb.Sheets[name]=ws;wb.SheetNames.push(name);return {ws,headerRow,lastRow};
  }
  function setNumFormats(ws,headerRow,lastRow,headers){const money=/rate|amount|contract amount|change rate/i;const pct=/progress/i;const qty=/qty|quantity|previous|current|cumulative|balance|norm/i;headers.forEach((h,c)=>{for(let r=headerRow+1;r<=lastRow;r++){const cell=ws[XLSX.utils.encode_cell({r,c})];if(!cell||typeof cell.v!=='number')continue;cell.z=pct.test(h)?fmtPct:money.test(h)&&!/^.*quantity/i.test(h)?fmtMoney:qty.test(h)?fmtQty:cell.z;}})}
  function exportWorkbook(){
    if(!window.XLSX){alert('Excel export is not available yet. Please try again when the Excel module has loaded.');return}
    const p=project(),wb={SheetNames:[],Sheets:{}};
    const boqRows=itemsW().map((x,i)=>{const c=x.change||{};return [s(x.no),s(x.section),s(x.desc),s(x.unit),n(x.qty),n(x.rate),n(x.qty)*n(x.rate),s(x.quantityBasis),s(x.drawingReference),s(x.remarks),s(c.classification&&c.classification!=='Original BOQ Item'?c.classification:''),s(c.referenceNo),date(c.date),n(c.revisedQuantity),n(c.rate),s(c.status),s(c.originalItemRef),s(c.approvalReference),s(c.reason),s(c.remarks)];});
    let z=sheet(wb,'BOQ Master','CivilKosh — BOQ Master',['Item No.','Section','Work Description','Unit','BOQ Quantity','Rate (NPR)','Amount (NPR)','Quantity Basis','Drawing / Reference','Remarks','Change Classification','Change Reference','Change Date','Revised / Allowed Quantity','Change Rate (NPR)','Change Status','Original BOQ Item Ref.','Approval / Instruction Ref.','Justification','Change Remarks'],boqRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['Item No.','Section','Work Description','Unit','BOQ Quantity','Rate (NPR)','Amount (NPR)','Quantity Basis','Drawing / Reference','Remarks','Change Classification','Change Reference','Change Date','Revised / Allowed Quantity','Change Rate (NPR)','Change Status','Original BOQ Item Ref.','Approval / Instruction Ref.','Justification','Change Remarks']);
    const mbRows=[];itemsW().forEach((x,i)=>(x.measurementRecords||[]).forEach((r,j)=>{const bs=Array.isArray(r.breakdowns)?r.breakdowns:[];if(!bs.length)mbRows.push([`Record ${j+1}`,date(r.date),s(x.no),s(x.desc),s(r.location),s(r.note),s(r.drawingReference),n(r.measured),n(r.approved),n(r.previous),n(r.current),r.previous==null||r.current==null?null:(n(r.previous)||0)+(n(r.current)||0),s(r.remarks),'','','','','']);else bs.forEach((b,k)=>{const d=b.detail||b;mbRows.push([`Record ${j+1}`,date(r.date),s(x.no),s(x.desc),s(r.location),s(r.note),s(r.drawingReference),n(r.measured),n(r.approved),n(r.previous),n(r.current),r.previous==null||r.current==null?null:(n(r.previous)||0)+(n(r.current)||0),s(r.remarks),`Breakdown ${k+1}`,s(d.element||b.element),s(d.calculation||b.calculation),n(b.quantity??d.quantity),n(d.length),n(d.width),n(d.height??d.depth)]);});}));
    z=sheet(wb,'Measurement / MB','CivilKosh — Measurement / MB',['Record','Date','BOQ Item','Description','Location / Reference','Measurement Note','Drawing / Reference','Measured Quantity','Approved Quantity','Previous Quantity','Current Quantity','Cumulative Quantity','Remarks','Breakdown No.','Breakdown Element','Breakdown Calculation','Breakdown Quantity','Length','Width','Height / Depth'],mbRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['Record','Date','BOQ Item','Description','Location / Reference','Measurement Note','Drawing / Reference','Measured Quantity','Approved Quantity','Previous Quantity','Current Quantity','Cumulative Quantity','Remarks','Breakdown No.','Breakdown Element','Breakdown Calculation','Breakdown Quantity','Length','Width','Height / Depth']);
    const qaRows=itemsW().map((x,i)=>{const q=quantity(x,i);return [s(x.no),s(x.desc),s(x.unit),q.allowed,q.previous,q.current,q.cumulative,q.balance,q.progress,q.rate,q.currentAmount,q.cumulativeAmount]});
    z=sheet(wb,'Quantity Abstract','CivilKosh — Quantity Abstract',['Item','Description','Unit','BOQ / Allowed Quantity','Previous','Current','Cumulative','Balance','Progress %','Rate (NPR)','Current Amount (NPR)','Cumulative Amount (NPR)'],qaRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['Item','Description','Unit','BOQ / Allowed Quantity','Previous','Current','Cumulative','Balance','Progress %','Rate (NPR)','Current Amount (NPR)','Cumulative Amount (NPR)']);
    const raRows=[];itemsW().forEach(x=>{const ra=x.rateAnalysis||{};['materials','labour','equipment','other'].forEach(k=>(Array.isArray(ra[k])?ra[k]:[]).forEach((r,i)=>raRows.push([s(x.no),s(x.desc),k==='materials'?'Material':k==='labour'?'Labour':k==='equipment'?'Equipment':'Other',s(r.description),s(r.unit),n(r.norm),n(r.rate),n(r.norm)*n(r.rate),s(r.source)])));if(raRows.filter(r=>r[0]===s(x.no)).length===0&&((ra.overhead!=null)||(ra.profit!=null)||(ra.source)))raRows.push([s(x.no),s(x.desc),'Rate Analysis Summary',s(ra.source),'',null,null,null,s(`Overhead ${ra.overhead??''}% · Profit ${ra.profit??''}%`)]);});
    z=sheet(wb,'Rate Analysis','CivilKosh — Rate Analysis',['BOQ Item','BOQ Description','Component Type','Component','Unit','Norm / Qty per BOQ Unit','Component Rate (NPR)','Amount (NPR)','Source / Reference'],raRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['BOQ Item','BOQ Description','Component Type','Component','Unit','Norm / Qty per BOQ Unit','Component Rate (NPR)','Amount (NPR)','Source / Reference']);
    const ipcRows=[];const groups=new Map();itemsW().forEach((item,i)=>(item.ipcRecords||[]).forEach(r=>{if(!r?.no)return;if(!groups.has(r.no))groups.set(r.no,{r,items:[]});const saved=Array.isArray(r.items)?r.items.find(v=>v.itemIndex===i):null;groups.get(r.no).items.push({item,i,current:n(saved?.current)||0});}));
    [...groups.values()].sort((a,b)=>(typeof ipcOrdinal==='function'?ipcOrdinal(a.r.no):0)-(typeof ipcOrdinal==='function'?ipcOrdinal(b.r.no):0)).forEach(g=>{const r=g.r,rows=g.items;const summary=rows.reduce((a,x)=>{const item=x.item,q=quantity(item,x.i);return {previous:a.previous+q.previous,current:a.current+x.current,cumulative:a.cumulative+q.previous+x.current}}, {previous:0,current:0,cumulative:0});const deductions=(n(r.retention)||0)+(n(r.advance)||0)+(n(r.deduction)||0),addition=n(r.addition)||0,net=summary.current-deductions+addition;rows.forEach(x=>{const item=x.item,idx=x.i,prev=typeof ipcPrevQty==='function'?n(ipcPrevQty(item,r.no))||0:0,cum=prev+x.current,rate=n(item.rate)||0;ipcRows.push([s(r.no),date(r.date),s(r.period),s(r.previousIpcNo),s(item.no),s(item.desc),s(item.unit),n(item.qty),prev,x.current,cum,(n(item.qty)||0)-cum,rate,x.current*rate,cum*rate,(n(item.qty)||0-cum)*rate,n(r.retention)||0,n(r.advance)||0,n(r.deduction)||0,addition,net,s(r.certification?.preparedBy),s(r.certification?.checkedBy),s(r.certification?.recommendedBy),s(r.certification?.approvedBy),date(r.certification?.date),s(r.certification?.note)]);});});
    z=sheet(wb,'IPC / Running Bill','CivilKosh — IPC / Running Bill',['IPC No.','Bill Date','Billing / Measurement Period','Previous IPC No.','BOQ Item','Description','Unit','BOQ Quantity','Previous Quantity','Current Quantity','Cumulative Quantity','Balance Quantity','Rate (NPR)','Current Amount (NPR)','Cumulative Amount (NPR)','Balance Amount (NPR)','Retention (NPR)','Advance (NPR)','Deduction (NPR)','Addition (NPR)','Net Payable (NPR)','Prepared By','Checked By','Recommended By','Approved By','Certification Date','Certification Note'],ipcRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['IPC No.','Bill Date','Billing / Measurement Period','Previous IPC No.','BOQ Item','Description','Unit','BOQ Quantity','Previous Quantity','Current Quantity','Cumulative Quantity','Balance Quantity','Rate (NPR)','Current Amount (NPR)','Cumulative Amount (NPR)','Balance Amount (NPR)','Retention (NPR)','Advance (NPR)','Deduction (NPR)','Addition (NPR)','Net Payable (NPR)','Prepared By','Checked By','Recommended By','Approved By','Certification Date','Certification Note']);
    const varRows=itemsW().filter(x=>x.change&&x.change.classification&&x.change.classification!=='Original BOQ Item').map(x=>{const c=x.change;return [s(x.no),s(x.desc),s(c.classification),s(c.status),s(c.referenceNo),date(c.date),n(x.qty),n(c.revisedQuantity),n(c.rate),s(c.originalItemRef),s(c.approvalReference),s(c.reason),s(c.remarks)]});
    z=sheet(wb,'Variation / Extra / Substituted','CivilKosh — Variation / Extra / Substituted',['BOQ Item','Description','Classification','Status','Reference','Date','Original BOQ Quantity','Revised / Allowed Quantity','Change Rate (NPR)','Original BOQ Item Ref.','Approval / Instruction Ref.','Justification','Remarks'],varRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['BOQ Item','Description','Classification','Status','Reference','Date','Original BOQ Quantity','Revised / Allowed Quantity','Change Rate (NPR)','Original BOQ Item Ref.','Approval / Instruction Ref.','Justification','Remarks']);
    const evRows=[];const allIpcs=[...groups.values()].sort((a,b)=>(typeof ipcOrdinal==='function'?ipcOrdinal(a.r.no):0)-(typeof ipcOrdinal==='function'?ipcOrdinal(b.r.no):0));allIpcs.forEach(g=>(Array.isArray(g.r.supportingDocuments)?g.r.supportingDocuments:[]).forEach((d,i)=>evRows.push([`DOC-${i+1}`,s(g.r.no),s(d.name),s(d.status),s(d.reference),date(d.date),s(d.remarks||d.note)])));
    z=sheet(wb,'Evidence & Documents','CivilKosh — Evidence & Documents',['Evidence / Document Ref.','IPC No.','Document / Evidence','Status','Reference','Date','Remarks'],evRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['Evidence / Document Ref.','IPC No.','Document / Evidence','Status','Reference','Date','Remarks']);
    const total=itemsW().reduce((a,x)=>a+(n(x.qty)||0)*(n(x.rate)||0),0),current=itemsW().reduce((a,x,i)=>a+quantity(x,i).currentAmount,0),cumulative=itemsW().reduce((a,x,i)=>a+quantity(x,i).cumulativeAmount,0),variationCount=itemsW().filter(x=>x.change&&x.change.classification&&x.change.classification!=='Original BOQ Item').length,measurementCount=itemsW().reduce((a,x)=>a+(x.measurementRecords||[]).length,0),ipcCount=groups.size;
    const reportRows=[['Project',p.name],['Location',p.location],['Employer / Client',p.client],['Contractor',p.contractor],['Project / Reference No.',p.ref],['Work Order / Contract No.',p.workOrder],['BOQ Grand Total (NPR)',total],['Latest / Current IPC Amount (NPR)',current],['Cumulative Certified Amount (NPR)',cumulative],['BOQ Item Count',itemsW().length],['Measurement Record Count',measurementCount],['IPC Record Count',ipcCount],['Variation / Extra / Substituted Item Count',variationCount],['Detailed sheets','BOQ Master · Measurement / MB · Quantity Abstract · Rate Analysis · IPC / Running Bill · Variation / Extra / Substituted · Evidence & Documents']];
    z=sheet(wb,'Reports / Summary','CivilKosh — Reports / Summary',['Summary Metric','Value'],reportRows,p);setNumFormats(z.ws,z.headerRow,z.lastRow,['Summary Metric','Value']);
    ['BOQ Master','Measurement / MB','Quantity Abstract','Rate Analysis','IPC / Running Bill','Variation / Extra / Substituted','Evidence & Documents','Reports / Summary'].forEach(name=>{const ws=wb.Sheets[name];ws['!cols'][1]={wch:42};});
    const safe=s(p.name||'CivilKosh').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-+|-+$/g,'')||'CivilKosh';XLSX.writeFile(wb,`${safe}-Workbook.xlsx`,{bookType:'xlsx',cellDates:true});
  }
  window.downloadCivilKoshExcel=exportWorkbook;
})();