const BOQ_WORKSPACE_STORAGE_KEY='civilkosh_boq_workspace_v1';
const boqPersistenceProjectFields=['projectName','projectLocation','projectClient','projectContractor','preparedBy','projectDate','projectRef','documentType','projectType','workOrder','projectRemarks'];
const BOQ_ID_REGISTRY_VERSION=1;
let boqIdentityRegistry={version:BOQ_ID_REGISTRY_VERSION,itemIds:new Set(),measurementRecordIds:new Set()};
function syncBoqPersistenceDraft(){if(typeof ipcSync==='function'&&typeof ipcState!=='undefined'&&ipcState.record)ipcSync();if(typeof variationRead==='function'&&typeof editing!=='undefined'&&editing>=0&&items[editing])items[editing].change=variationRead()}
function identityId(prefix,used){let id;do{if(typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')id=`${prefix}-${crypto.randomUUID()}`;else if(typeof crypto!=='undefined'&&typeof crypto.getRandomValues==='function'){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);id=`${prefix}-${Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}`}else id=`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}while(used.has(id));used.add(id);return id}
function identityRegistry(state){const source=state&&state.idRegistry&&typeof state.idRegistry==='object'?state.idRegistry:{};const itemIds=new Set(Array.isArray(source.itemIds)?source.itemIds.filter(v=>typeof v==='string'&&v):[]);const measurementRecordIds=new Set(Array.isArray(source.measurementRecordIds)?source.measurementRecordIds.filter(v=>typeof v==='string'&&v):[]);return{version:BOQ_ID_REGISTRY_VERSION,itemIds,measurementRecordIds}}
function migrateStableIds(state){const sourceRegistry=identityRegistry(state);const registry={version:sourceRegistry.version,itemIds:new Set([...boqIdentityRegistry.itemIds,...sourceRegistry.itemIds]),measurementRecordIds:new Set([...boqIdentityRegistry.measurementRecordIds,...sourceRegistry.measurementRecordIds])};const seenItemIds=new Set(),seenMeasurementRecordIds=new Set();const sourceItems=Array.isArray(state?.items)?state.items:[];sourceItems.forEach(item=>{if(!item||typeof item!=='object')return;if(typeof item.id!=='string'||!item.id||seenItemIds.has(item.id)){item.id=identityId('ITEM',registry.itemIds)}else registry.itemIds.add(item.id);seenItemIds.add(item.id);const records=Array.isArray(item.measurementRecords)?item.measurementRecords:[];records.forEach(record=>{if(!record||typeof record!=='object')return;if(typeof record.id!=='string'||!record.id||seenMeasurementRecordIds.has(record.id))record.id=identityId('MB',registry.measurementRecordIds);else registry.measurementRecordIds.add(record.id);seenMeasurementRecordIds.add(record.id)})});boqIdentityRegistry=registry;return{version:registry.version,itemIds:Array.from(registry.itemIds),measurementRecordIds:Array.from(registry.measurementRecordIds)}}
function boqWorkspaceState(){syncBoqPersistenceDraft();const state={version:1,sections:Array.isArray(sections)?sections:[],items:Array.isArray(items)?items:[],project:Object.fromEntries(boqPersistenceProjectFields.map(id=>[id,$(id)?.value??''])),ipcState:typeof ipcState!=='undefined'?ipcState:null};state.idRegistry=migrateStableIds(state);return state;}
function saveBoqWorkspace(){try{localStorage.setItem(BOQ_WORKSPACE_STORAGE_KEY,JSON.stringify(boqWorkspaceState()))}catch(e){console.warn('CivilKosh workspace persistence unavailable',e)}}
function restoreBoqWorkspace(){try{const raw=localStorage.getItem(BOQ_WORKSPACE_STORAGE_KEY);if(!raw)return false;const state=JSON.parse(raw);if(!state||!Array.isArray(state.items))return false;state.idRegistry=migrateStableIds(state);localStorage.setItem(BOQ_WORKSPACE_STORAGE_KEY,JSON.stringify(state));sections=Array.isArray(state.sections)&&state.sections.length?state.sections:sections;items=state.items;editing=-1;itemMode='idle';boqPersistenceProjectFields.forEach(id=>{const el=$(id);if(el&&state.project&&Object.prototype.hasOwnProperty.call(state.project,id))el.value=state.project[id]});if(typeof ipcState!=='undefined'&&state.ipcState)ipcState=state.ipcState;populateSections($('itemSection')?.value);renderCustomSections();render();if(typeof rateAnalysisRender==='function')rateAnalysisRender();if(typeof ipcRender==='function')ipcRender();let selectedIndex=Number($('measurementItem')?.value);if(!Number.isInteger(selectedIndex)||!items[selectedIndex])selectedIndex=items.reduce((last,x,i)=>Array.isArray(x.measurementRecords)&&x.measurementRecords.length?i:last,-1);const selectedItem=Number.isInteger(selectedIndex)&&selectedIndex>=0?items[selectedIndex]:null;const records=selectedItem?.measurementRecords||[];if(selectedItem&&records.length&&typeof editMeasurementRecord==='function')editMeasurementRecord(selectedIndex,records.length-1);return true}catch(e){console.warn('CivilKosh workspace restore failed',e);return false}}
function clearBoqWorkspacePersistence(){try{localStorage.removeItem(BOQ_WORKSPACE_STORAGE_KEY)}catch(e){}}
let boqPersistenceTimer;
function scheduleBoqWorkspaceSave(){clearTimeout(boqPersistenceTimer);boqPersistenceTimer=setTimeout(saveBoqWorkspace,50)}
document.addEventListener('DOMContentLoaded',()=>{restoreBoqWorkspace();if(typeof initIPC==='function')initIPC();document.addEventListener('input',scheduleBoqWorkspaceSave);document.addEventListener('change',scheduleBoqWorkspaceSave);document.addEventListener('click',e=>{if(e.target.closest('#resetBoq')){setTimeout(clearBoqWorkspacePersistence,0);return}scheduleBoqWorkspaceSave()});const s=document.createElement('script');s.src='measurement-mb.js';s.onload=()=>window.measurementMbRefresh?.();document.body.appendChild(s);});
