'use strict';
const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const crypto=require('crypto').webcrypto;
const source=fs.readFileSync(__dirname+'/persistence.js','utf8');
const context={console,crypto,Uint8Array,Set,Math,Date,Object,JSON,Array,document:{addEventListener(){}},window:{},localStorage:{setItem(){},getItem(){return null},removeItem(){}},sections:[],items:[],editing:-1,itemMode:'idle',ipcState:null,$(){return null},setTimeout,clearTimeout};
vm.createContext(context);
vm.runInContext(source,context,{filename:'persistence.js'});
assert.strictEqual(typeof context.migrateStableIds,'function');
function migrate(state){context.boqIdentityRegistry={version:1,itemIds:new Set(),measurementRecordIds:new Set()};return context.migrateStableIds(state)}
const legacy={items:[{no:'1',desc:'A',qty:10},{no:'2',desc:'B',qty:20,id:'ITEM-existing'}]};
const before=JSON.parse(JSON.stringify(legacy));
const registry1=migrate(legacy);
assert.ok(legacy.items[0].id);
assert.strictEqual(legacy.items[1].id,'ITEM-existing');
assert.notStrictEqual(legacy.items[0].id,legacy.items[1].id);
assert.strictEqual(legacy.items[0].no,before.items[0].no);
assert.strictEqual(legacy.items[0].desc,before.items[0].desc);
assert.deepStrictEqual(registry1.itemIds.sort(),[legacy.items[0].id,'ITEM-existing'].sort());
const itemIds=legacy.items.map(x=>x.id);
const state2={items:legacy.items};
const registry2=migrate(state2);
assert.deepStrictEqual(state2.items.map(x=>x.id),itemIds);
assert.deepStrictEqual(registry2.itemIds.sort(),registry1.itemIds.sort());
state2.items.reverse();
const reorderedIds=state2.items.map(x=>x.id);
assert.deepStrictEqual(reorderedIds.sort(),itemIds.slice().sort());
assert.strictEqual(new Set(reorderedIds).size,reorderedIds.length);
state2.items[0].measurementRecords=[{current:1},{current:2,id:'MB-existing'}];
state2.items[1].measurementRecords=[{current:3}];
migrate(state2);
const allRecords=state2.items.flatMap(x=>x.measurementRecords);
assert.ok(allRecords[0].id);
assert.strictEqual(state2.items[0].measurementRecords[1].id,'MB-existing');
assert.strictEqual(new Set(allRecords.map(x=>x.id)).size,allRecords.length);
const mbIds=allRecords.map(x=>x.id);
migrate(state2);
assert.deepStrictEqual(state2.items.flatMap(x=>x.measurementRecords).map(x=>x.id),mbIds);
const recordPair=state2.items[0].measurementRecords.map(x=>x.id);
state2.items[0].measurementRecords.reverse();
assert.deepStrictEqual(state2.items[0].measurementRecords.map(x=>x.id).sort(),recordPair.sort());
const compatibility={items:[{no:'10',itemIndex:7,measurementRecords:[{recordIndex:4,current:5,custom:'keep'}],customItem:'keep'}]};
migrate(compatibility);
assert.strictEqual(compatibility.items[0].itemIndex,7);
assert.strictEqual(compatibility.items[0].customItem,'keep');
assert.strictEqual(compatibility.items[0].measurementRecords[0].recordIndex,4);
assert.strictEqual(compatibility.items[0].measurementRecords[0].custom,'keep');
const duplicate={items:[{id:'ITEM-dup'},{id:'ITEM-dup'}]};
migrate(duplicate);
assert.strictEqual(duplicate.items[0].id,'ITEM-dup');
assert.notStrictEqual(duplicate.items[1].id,'ITEM-dup');
assert.strictEqual(new Set(duplicate.items.map(x=>x.id)).size,2);
console.log('stable ID migration tests: PASS');
