(function(){
  'use strict';
  if(window.__civilKoshWorkbookInstalled)return;
  window.__civilKoshWorkbookInstalled=true;
  const escW=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const numW=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
  const fmtW=v=>typeof fmt==='function'?fmt(numW(v)):numW(v).toFixed(2);
  const moneyW=v=>typeof money==='function'?money(v):`NPR ${fmtW(v)}`;
  const navItems=[['boqMaster','BOQ Master'],['measurementMb','Measurement / MB'],['quantityAbstract','Quantity Abstract'],['rateAnalysisRoot','Rate Analysis'],['ipcRoot','IPC / Running Bill'],['variationSection','Variation / Extra / Substituted'],['evidenceSection','Evidence & Documents'],['reportsPrint','Reports / Print']];
  function installStyle(){if(document.getElementById('civilkoshWorkbookStyle'))return;const style=document.createElement('style');style.id='civilkoshWorkbookStyle';style.textContent=`
    .ck-workbook-nav{position:sticky;top:0;z-index:20;margin:0 0 12px;padding:7px 8px;border:1px solid #c9cfcc;background:rgba(247,249,248,.96);backdrop-filter:blur(6px);box-shadow:0 2px 8px rgba(32,37,34,.05)}
    .ck-workbook-nav-inner{display:flex;gap:6px;overflow-x:auto;scrollbar-width:thin;white-space:nowrap}
    .ck-workbook-nav a{display:inline-flex;align-items:center;min-height:30px;padding:5px 10px;border:1px solid #c7cdca;border-radius:4px;background:#fff;color:#303733;text-decoration:none;font-size:12px;font-weight:600}
    .ck-workbook-nav a:hover,.ck-workbook-nav a:focus{border-color:#68716c;background:#eef1ef;outline:none}
    #quantityAbstract{scroll-margin-top:58px;margin-top:12px}
    #quantityAbstract .panel-head{margin-bottom:5px}
    .ck-abstract-note{font-size:12px;color:#5b635e;margin:0 0 8px}
    .ck-abstract-wrap{overflow-x:auto}
    .ck-abstract-table{min-width:1180px;font-size:11.5px}
    .ck-abstract-table th,.ck-abstract-table td{padding:5px 6px;vertical-align:middle}
    .ck-abstract-table th{white-space:nowrap}
    .ck-abstract-table td.num{white-space:nowrap}
    .ck-abstract-table .ck-progress{min-width:72px}
    #boqMaster,#measurementMb,#rateAnalysisRoot,#ipcRoot,#variationSection,#evidenceSection,#reportsPrint{scroll-margin-top:58px}
    @media(max-width:700px){.ck-workbook-nav{margin-left:-4px;margin-right:-4px}.ck-workbook-nav a{font-size:11px;padding:5px 8px}.ck-abstract-table{font-size:11px}}
  `;document.head.appendChild(style)}
  function ensureAnchor(id,element){if(!element)return null;element.id=id;return element}
  function locateAnchors(){const layout=document.querySelector('.boq-layout');ensureAnchor('boqMaster',layout);ensureAnchor('measurementMb',document.querySelector('.summary-grid'));const rate=document.getElementById('rateAnalysisRoot');if(rate)ensureAnchor('rateAnalysisRoot',rate);const ipc=document.getElementById('ipcRoot');if(ipc)ensureAnchor('ipcRoot',ipc);const variation=document.querySelector('[data-variation-fields]');if(variation)ensureAnchor('variationSection',variation);const evidence=ipc?[...ipc.querySelectorAll('details')].find(x=>/IPC Evidence \/ Document Register/i.test(x.querySelector('summary')?.textContent||'')):null;if(evidence)ensureAnchor('evidenceSection',evidence);const reports=document.querySelector('.boq-actions');if(reports)ensureAnchor('reportsPrint',reports)}
  function renderNav(){locateAnchors();const host=document.querySelector('.boq-section>.container');if(!host)return;let nav=document.getElementById('civilkoshWorkbookNav');if(!nav){nav=document.createElement('nav');nav.id='civilkoshWorkbookNav';nav.className='ck-workbook-nav';nav.setAttribute('aria-label','Project workbook sections');const inner=document.createElement('div');inner.className='ck-workbook-nav-inner';nav.appendChild(inner);host.insertBefore(nav,host.firstElementChild)}const inner=nav.firstElementChild;inner.innerHTML=navItems.map(([id,label])=>`<a href="#${id}" data-workbook-target="${id}">${label}</a>`).join('');inner.querySelectorAll('a').forEach(a=>a.addEventListener('click',e=>{const target=document.getElementById(a.dataset.workbookTarget);if(!target)return;e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',`#${a.dataset.workbookTarget}`)}))}
  function savedRows(item,index){const records=Array.isArray(item?.ipcRecords)?item.ipcRecords.filter(r=>r&&r.no):[];const byNo=new Map();records.forEach(r=>{if(!byNo.has(r.no))byNo.set(r.no,r)});const unique=[...byNo.values()].sort((a,b)=>(typeof ipcOrdinal==='function'?ipcOrdinal(a.no):0)-(typeof ipcOrdinal==='function'?ipcOrdinal(b.no):0));const active=typeof ipcState!=='undefined'?ipcState.record:null;let previous=0,current=0;if(active?.editingNo){previous=typeof ipcPrevQty==='function'?ipcPrevQty(item,active.editingNo):unique.filter(r=>(typeof ipcOrdinal==='function'?ipcOrdinal(r.no):0)<(typeof ipcOrdinal==='function'?ipcOrdinal(active.editingNo):0)).reduce((s,r)=>s+numW(r.items?.find(x=>x.itemIndex===index)?.current),0);current=numW(active.items?.find(x=>x.itemIndex===index)?.current)}else if(active?.no&&Array.isArray(active.items)&&active.items.length){previous=unique.reduce((s,r)=>s+numW(r.items?.find(x=>x.itemIndex===index)?.current),0);current=numW(active.items.find(x=>x.itemIndex===index)?.current)}else if(unique.length){const latest=unique[unique.length-1];current=numW(latest.items?.find(x=>x.itemIndex===index)?.current);previous=unique.slice(0,-1).reduce((s,r)=>s+numW(r.items?.find(x=>x.itemIndex===index)?.current),0)}const cumulative=previous+current;const limit=typeof variationAllowedQty==='function'?numW(variationAllowedQty(item)):numW(item.qty);const balance=limit-cumulative;const progress=limit>0?Math.max(0,cumulative/limit*100):0;return{previous,current,cumulative,limit,balance,progress,previousAmount:previous*numW(item.rate),currentAmount:current*numW(item.rate),cumulativeAmount:cumulative*numW(item.rate)}}
  function renderAbstract(){if(typeof items==='undefined')return;const host=document.getElementById('quantityAbstract');if(!host||!Array.isArray(items))return;const source=items;const rows=source.map((item,i)=>({item,data:savedRows(item,i)}));host.innerHTML=`<div class="panel-head"><div><span class="panel-kicker">QUANTITY ABSTRACT</span><h2>Certified Quantity &amp; Payment Bridge</h2></div><span class="panel-note">Linked to saved Measurement / MB and IPC history</span></div><p class="ck-abstract-note">Certified quantities are derived from the existing saved IPC history; Measurement / MB remains the supporting quantity and verification source. No duplicate quantity entry is required here.</p><div class="ck-abstract-wrap"><table class="boq-table ck-abstract-table"><thead><tr><th>Item No.</th><th>Description</th><th>Unit</th><th class="num">BOQ Qty</th><th class="num">Previous Certified Qty</th><th class="num">Current Certified Qty</th><th class="num">Cumulative Certified Qty</th><th class="num">Balance Qty</th><th class="num">Rate</th><th class="num">Previous Amount</th><th class="num">Current Amount</th><th class="num">Cumulative Amount</th><th class="num ck-progress">Progress %</th></tr></thead><tbody>${rows.length?rows.map(({item,data})=>`<tr><td>${escW(item.no)}</td><td>${escW(item.desc)}</td><td>${escW(item.unit)}</td><td class="num">${fmtW(item.qty)}</td><td class="num">${fmtW(data.previous)}</td><td class="num">${fmtW(data.current)}</td><td class="num">${fmtW(data.cumulative)}</td><td class="num">${fmtW(data.balance)}</td><td class="num">${moneyW(item.rate)}</td><td class="num">${moneyW(data.previousAmount)}</td><td class="num">${moneyW(data.currentAmount)}</td><td class="num">${moneyW(data.cumulativeAmount)}</td><td class="num">${fmtW(data.progress)}%</td></tr>`).join(''):'<tr><td colspan="13">No saved BOQ items yet.</td></tr>'}</tbody></table></div>`}
  function installAbstract(){const summary=document.querySelector('.summary-grid');if(!summary||document.getElementById('quantityAbstract'))return;const section=document.createElement('section');section.id='quantityAbstract';section.className='boq-panel';summary.after(section);renderAbstract()}
  function install(){installStyle();installAbstract();renderNav();const originalRender=window.render;if(typeof originalRender==='function'&&!originalRender.__workbookWrapped){const wrapped=function(){const result=originalRender.apply(this,arguments);renderAbstract();renderNav();return result};wrapped.__workbookWrapped=true;window.render=wrapped}const originalIpcRender=window.ipcRender;if(typeof originalIpcRender==='function'&&!originalIpcRender.__workbookWrapped){const wrapped=function(){const result=originalIpcRender.apply(this,arguments);renderAbstract();renderNav();return result};wrapped.__workbookWrapped=true;window.ipcRender=wrapped}const observer=new MutationObserver(()=>{if(!document.getElementById('quantityAbstract'))installAbstract();locateAnchors()});const root=document.querySelector('.boq-section>.container');if(root)observer.observe(root,{childList:true,subtree:true})}
  document.addEventListener('DOMContentLoaded',install);
})();
